version: 2.1
jobs:
  #build:
    #...
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "c1:9c:8a:41:1a:38:42:16:b3:d1:1e:48:ac:c6:30:4d"
      - run:
          name: Deploy Over SSH
          command: |
             ssh $SSH_USER@$SSH_HOST "cd hello-circleci && git pull && echo hello " 

workflows:
  version: 2
  build-and-deploy:
    jobs:
      #- build
      - deploy:
          #requires:
          #  - build # only deploy once build job has completed
          filters:
            branches:
              only: master # only deploy on the master branch